### ISSUE TITLE
This adds iron router package?

### ISSUE THREAD

**Issue by JulianKingman** [meteor-useraccounts/foundation#5]
I installed this package and noticed that it also installs the iron router package, which I didn't want or need. Is that necessary, or a mistake? I also didn't see it on the dependencies listed, so it took me a bit to find which package had installed it.

**Comment by splendido** [comment]
It's `useraccounts:core` actually depending on it...
But there's a [`flow-router-integration`](https://github.com/meteor-useraccounts/core/tree/flow-router-integration) branch just updated to `kadira:flow-router@2` if you wish to try it out ;-)

`useraccounts@2.0` will come with no routing features as default, so this will be solved soon!

**Comment by JulianKingman** [comment]
Thanks!
