### ISSUE TITLE
Foundation 6 Support

### ISSUE THREAD

**Issue by venetianthief** [meteor-useraccounts/foundation#6]
Any plans for Foundation 6 support? Would that require a separate package?

**Comment by splendido** [comment]
@venetianthief I'm sorry I still had no time to have a look at it.

After a quick test it seems there are some classes to be changed within the templates: if we update them for Foundation 6 then `useraccounts:foundation` won't work for Foundation 5...

Perhaps a `useraccounts:foundation-sites` package?
Would you be willing to help if I give you some pointers? :-)

**Comment by venetianthief** [comment]
@splendido Yes, I would be willing to help out although I will not be able to invest time until after Jan 3rd due to current project.

**Comment by venetianthief** [comment]
@splendido I'm available now. Can you point me in the right direction to get started on this? Thanks! :)

**Comment by dstollie** [comment]
@venetianthief It would be really cool if you could get some time to fix this. currently im not in the position to fix this but if I would. I would have forked this repository and refactor the html files so that it works conform foundation 6. No rocket science but a crucial step for me to go with this package

**Comment by splendido** [comment]
@venetianthief any news on this?

@dstollie is right this should be the sequence of things to be done:
* create a new repo
* initialize it with the content of `useraccounts:foundation`
* look for .html files (see [here](https://github.com/meteor-useraccounts/foundation/tree/master/lib))
* change elements' class attributes to conform with Foundation6 specs
* transfer ownership to `meteor-useraccounts` when ready ;-)

You can test it locally while you change stuff running one of the [boilerplates](https://github.com/meteor-useraccounts/boilerplates) (ask me if you need further help with this...)

**Comment by venetianthief** [comment]
@splendido I nearly forgot about this so I went ahead and made the changes tonight. I cannot transfer ownership to an organization that I do not have admin rights.

I went ahead and updated the `package.js` and `README.md `and replaced any indication of `foundation` with `foundation-sites`. I left the version number at `1.13.1` to keep it consistent with the rest of the packages. Let me know if anything else needs to be done. :)

See https://github.com/venetianthief/foundation-sites

**Comment by creativekinetix** [comment]
Any word on getting this added as a package so it can be added to a project?

**Comment by splendido** [comment]
@venetianthief you should now be able to transfer the repo, let me know when you're done.
Thanks for all the work you put on this!

**Comment by venetianthief** [comment]
@splendido Done

**Comment by splendido** [comment]
awesome!
...I'll try to bump a new version the next week including the new `useraccounts:foundation-sites`

I know things are getting slower and slower with `useraccounts` packages, I'm sorry for this.

**Comment by venetianthief** [comment]
Sounds good! :+1:

**Comment by splendido** [comment]
It's been eventually published! Please lets have a look at it.
I'm really sorry for the delay, hope everything's good now.

**Comment by splendido** [comment]
See [releases for useraccounts:foundation-sites](https://github.com/meteor-useraccounts/foundation-sites/releases) and [useraccounts:foundation-sites on atmosphere](https://atmospherejs.com/useraccounts/foundation-sites)
